[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
via_ir = false


remappings = [
    "@superfluid-finance/ethereum-contracts/=lib/superfluid-protocol-monorepo/packages/ethereum-contracts/",
    "@superfluid-finance/solidity-semantic-money/=lib/superfluid-protocol-monorepo/packages/solidity-semantic-money/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-v4/contracts/",
    "@openzeppelin-v5/contracts/=lib/openzeppelin-contracts-v5/contracts/"
]


[fmt]
bracket_spacing = true
sort_imports = true
contract_new_lines = true
line_length = 120
number_underscore = "thousands"
wrap_comments = true